language: python
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:js-reynaud/ppa-kicad -y
  - sudo apt-get update -q
  - sudo apt-get install kicad cabal-install -y
script:
  - echo $PYTHON_PATH
  - export PYTHON_PATH=$PYTHON_PATH:/usr/lib/python2.7/dist-packages
  - ls /usr/lib/python2.7/pcbnew.py
  - python test.py
