language: python
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:js-reynaud/ppa-kicad -y
  - sudo apt-get update -q
  - sudo apt-get install kicad cabal-install -y
script:
  - sudo find / -name pcbnew.py
  - python test.py
