sudo: required
language: python
dist: trusty
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - sudo add-apt-repository ppa:js-reynaud/ppa-kicad -y
  - sudo apt-get update -q
  - sudo apt-get install kicad cabal-install -y
script:
  - stack build
  - stack test
  - bash keep_alive.sh &
  - PYTHONPATH=/usr/lib/python2.7/dist-packages ./parse_all_footprints
